<a href="https://colab.research.google.com/github/26wh5a0503-hash/NASSCOM/blob/main/WEEK%202/NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")

arr1_1 = np.arange(100)
arr1_2 = np.ones((3, 3))
arr1_3 = np.full((2, 4), 7)
arr1_4 = np.random.randint(10, 51, size=(5, 5))

print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])


# Task 2: Indexing and Slicing with Arrays
print("\n--- Task 2: Indexing and Slicing with Arrays ---")

data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])

val2_1 = data[2, 3]
row2_2 = data[0]
col2_3 = data[:, -1]
sub_arr2_4 = data[1:3, 0:2]
filtered_elements2_5 = data[data > 100]

print("val2_1:", val2_1)
print("row2_2:", row2_2)
print("col2_3:", col2_3)
print("sub_arr2_4:\n", sub_arr2_4)
print("filtered_elements2_5:", filtered_elements2_5)


# Task 3: Conditional Operations
print("\n--- Task 3: Conditional Operations ---")

arr3_1 = np.random.randint(1, 21, size=(4, 5))

arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)
even_count3_3 = np.sum(arr3_1 % 2 == 0)

print("arr3_1:\n", arr3_1)
print("arr3_2:\n", arr3_2)
print("even_count3_3:", even_count3_3)


# Task 4: Aggregation Functions
print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])

sum4_1 = np.sum(arr4_1)
mean_cols4_2 = np.mean(arr4_1, axis=0)
max_rows4_3 = np.max(arr4_1, axis=1)
std4_4 = np.std(arr4_1)

print("sum4_1:", sum4_1)
print("mean_cols4_2:", mean_cols4_2)
print("max_rows4_3:", max_rows4_3)
print("std4_4:", std4_4)


# Task 5: Reshaping and Flattening
print("\n--- Task 5: Reshaping and Flattening ---")

arr5_1 = np.arange(24)

reshaped_arr5_2 = arr5_1.reshape(4, 6)
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)
flattened_arr5_4 = reshaped_arr5_2.ravel()

# Using flatten() also
flattened_arr5_4_flatten = reshaped_arr5_2.flatten()

print("reshaped_arr5_2:\n", reshaped_arr5_2)
print("reshaped_arr5_3:\n", reshaped_arr5_3)
print("flattened_arr5_4:", flattened_arr5_4)


# Task 6: Broadcasting
print("\n--- Task 6: Broadcasting ---")

arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

scalar = 10
vector = np.array([100, 200, 300])

result6_1 = arr6_1 + scalar
result6_2 = arr6_1 + vector

print("result6_1:\n", result6_1)
print("result6_2:\n", result6_2)


# Task 7: Copying vs. Viewing Arrays
print("\n--- Task 7: Copying vs. Viewing Arrays ---")

original_arr7 = np.array([1, 2, 3, 4, 5])

view_arr7 = original_arr7[:]
view_arr7[0] = 99

print("view_arr7:", view_arr7)
print("original_arr7 after modifying view:", original_arr7)

copy_arr7 = original_arr7.copy()
copy_arr7[-1] = 0

print("copy_arr7:", copy_arr7)
print("original_arr7 after modifying copy:", original_arr7)

# Task 8: Stacking and Splitting Arrays
print("\n--- Task 8: Stacking and Splitting Arrays ---")

arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])

# 8.1 Vertically stack arr8_a and arr8_b
vstack_arr8_1 = np.vstack((arr8_a, arr8_b))

# 8.2 Horizontally stack arr8_a and arr8_b
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))

# 8.3 Vertically stack vstack_arr8_1 and arr8_c
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

# 8.4 Split into 3 parts
# 5 rows cannot be divided into 3 equal parts,
# so array_split is used instead of vsplit.
part1, part2, part3 = np.array_split(combined_arr8_3, 3)

print("vstack_arr8_1:\n", vstack_arr8_1)
print("hstack_arr8_2:\n", hstack_arr8_2)
print("combined_arr8_3:\n", combined_arr8_3)
print("part1:\n", part1)
print("part2:\n", part2)
print("part3:\n", part3)


--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[38 37 28 17 12]
 [46 20 33 22 33]]

--- Task 2: Indexing and Slicing with Arrays ---
val2_1: 120
row2_2: [10 20 30 40]
col2_3: [ 40  80 120 160]
sub_arr2_4:
 [[ 50  60]
 [ 90 100]]
filtered_elements2_5: [110 120 130 140 150 160]

--- Task 3: Conditional Operations ---
arr3_1:
 [[ 5 12 12  8 16]
 [11  3 12 11  6]
 [12  1 14 12  6]
 [ 9 19 13  6 10]]
arr3_2:
 [[ 0 12 12  0 16]
 [11  0 12 11  0]
 [12  0 14 12  0]
 [ 0 19 13  0 10]]
even_count3_3: 12

--- Task 4: Aggregation Functions ---
sum4_1: 84
mean_cols4_2: [11.          6.66666667 10.33333333]
max_rows4_3: [12 15 20]
std4_4: 5.2493385826745405

--- Task 5: Reshaping and Flattening ---
reshaped_arr5_2:
 [[ 0  1  2  